# Generated by Django 2.2.4 on 2019-08-27 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.FloatField(max_length=5)),
                ('description', models.TextField(max_length=200)),
                ('size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('X', 'X Size'), ('XXL', 'XXL Size')], max_length=3, null=True)),
                ('color', models.CharField(choices=[('R', 'Red'), ('B', 'BLUE'), ('BL', 'BLACK'), ('O', 'Orange'), ('P', 'Purple')], max_length=2)),
            ],
        ),
    ]
