# Generated by Django 2.2.4 on 2019-08-27 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='slug',
            field=models.SlugField(default='Test-product', max_length=10),
            preserve_default=False,
        ),
    ]
