# Generated by Django 2.2.4 on 2019-08-27 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_products_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('WT', 'Watches'), ('CL', 'Clothing'), ('JW', 'Jewelry'), ('SH', 'Shoes')], default='Watches', max_length=2),
            preserve_default=False,
        ),
    ]
