# Generated by Django 2.2.4 on 2019-08-28 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_products_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='ratings',
            field=models.IntegerField(default='3'),
            preserve_default=False,
        ),
    ]
