# Generated by Django 2.2.4 on 2019-08-30 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0004_products_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.ImageField(default='img', upload_to='Products-Images'),
            preserve_default=False,
        ),
    ]
